name: Blob storage website CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
            az storage blob upload-batch --account-name htechaueprodweb --subscription ${{ secrets.AZURE_SUBSCRIPTION }} --auth-mode key -d '$web' -s .
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "htech-aue-prod-web-cdn" --name "htech-aue-prod-web-cdn" --resource-group "htech-infra-aue-prod-rg"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
